package com.tgw.stock.ui.nav

object Routes {
    const val DASHBOARD = "dashboard"
    const val STOCK_LIST = "stock"
    const val PRODUCT_DETAIL = "stock/{productId}"
    const val PRODUCT_EDIT = "stock/{productId}/edit"
    const val PRODUCT_ADD = "stock/add?barcode={barcode}"
    const val STOCK_IN = "stockIn?productId={productId}"
    const val STOCK_OUT = "stockOut?productId={productId}"
    const val STOCK_COUNT_LIST = "stockCounts"
    const val STOCK_COUNT_DETAIL = "stockCounts/{countId}"
    const val RECIPE_LIST = "recipes"
    const val RECIPE_DETAIL = "recipes/{recipeId}"
    const val RECIPE_ADD = "recipes/add"
    const val SUPPLIER_LIST = "suppliers"
    const val SUPPLIER_DETAIL = "suppliers/{supplierId}"
    const val SUPPLIER_ADD = "suppliers/add"
    const val SUPPLIER_EDIT = "suppliers/{supplierId}/edit"
    const val SUPPLIER_PRICES = "supplierPrices/{productId}"
    const val PURCHASE_LIST = "purchase"
    const val PURCHASE_ORDER_LIST = "purchaseOrders"
    const val PURCHASE_ORDER_DETAIL = "purchaseOrders/{orderId}"
    const val PURCHASE_ORDER_NEW = "purchaseOrders/new?supplierId={supplierId}"
    const val WASTE = "waste"
    const val REPORTS = "reports"
    const val SETTINGS = "settings"
    const val MORE = "more"
    const val BARCODE_SCAN = "barcodeScan"

    fun productDetail(id: Long) = "stock/$id"
    fun productEdit(id: Long) = "stock/$id/edit"
    fun productAdd(barcode: String? = null) = if (barcode != null) "stock/add?barcode=$barcode" else "stock/add?barcode="
    fun stockIn(productId: Long? = null) = if (productId != null) "stockIn?productId=$productId" else "stockIn"
    fun stockOut(productId: Long? = null) = if (productId != null) "stockOut?productId=$productId" else "stockOut"
    fun stockCountDetail(id: Long) = "stockCounts/$id"
    fun recipeDetail(id: Long) = "recipes/$id"
    fun supplierDetail(id: Long) = "suppliers/$id"
    fun supplierEdit(id: Long) = "suppliers/$id/edit"
    fun supplierPrices(productId: Long) = "supplierPrices/$productId"
    fun purchaseOrderDetail(id: Long) = "purchaseOrders/$id"
    fun purchaseOrderNew(supplierId: Long? = null) =
        if (supplierId != null) "purchaseOrders/new?supplierId=$supplierId" else "purchaseOrders/new"
}
